version: '1'

services:
  db:
    image: postgres  
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: root
    volumes:
      - ./data:/var/lib/postgresql/data 

  adminer:
    image: adminer
    restart: always
    ports:
      - 8880:8080