version: "3"

services:

  adminer:
    image: adminer
    ports:
      - 8888:8080

  db:
    image: "mysql:8.0.33"
    ports:
      - 3306:3306
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: db

